name: "Eventide component workflow: build and push"

on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      force_push_image:
        required: false
        type: boolean
        default: false

    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM:
        required: true
      BUNDLE_GITHUB__COM:
        required: false
      GCLOUD_PROJECT_ID:
        required: true

jobs:
  build:
    env:
      IMAGEBASE: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ inputs.component_name }}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGHOST: postgres
      PGUSER: postgres
      EVENTIDE_DATABASE_URL: postgres://message_store@postgres/message_store
      DATABASE_URL: postgres://postgres@postgres:5432

    runs-on: self-hosted

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set branch
        run: echo "branch=${GITHUB_REF_NAME:-$(git branch | grep "\*" | cut -d\  -f2)}" >> $GITHUB_ENV

      - name: Set commit_sha
        run: echo "commit_sha=${GITHUB_SHA:-$(git rev-parse HEAD)}" >> $GITHUB_ENV

      - name: Set imagetag
        run: echo "imagetag=${IMAGETAG:-${{ env.branch }}-$(date +%Y-%m-%d-%H-%M-%z |sed -e 's/+//')-$(echo "${{ env.commit_sha }}"|cut -c1-8)}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and export to Docker (to GCP in master)
        uses: docker/build-push-action@v3
        with:
          load: ${{ !(github.ref == 'refs/heads/master') }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: |
            ${{ env.IMAGEBASE }}:master
          tags: |
            ${{ env.IMAGEBASE }}:${{ env.imagetag }}
            ${{ env.IMAGEBASE }}:latest
          labels: |
            ${{ inputs.component_name }}
          build-args: |
            POSTURE=${{ github.ref == 'refs/heads/master' && 'operational' || 'dev' }}
          secrets: |
            BUNDLE_RUBYGEMS__PKG__GITHUB__COM=${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
            BUNDLE_GITHUB__COM=${{ secrets.BUNDLE_GITHUB__COM }}

      - name: Tests
        run: |
          docker run --network "${{ job.container.network }}" \
            --env POSTGRES_HOST_AUTH_METHOD=$POSTGRES_HOST_AUTH_METHOD \
            --env PGHOST=$PGHOST \
            --env PGUSER=$PGUSER \
            --env EVENTIDE_DATABASE_URL=$EVENTIDE_DATABASE_URL \
            --env DATABASE_URL=$DATABASE_URL \
            --rm ${{ env.IMAGEBASE }}:${{ env.imagetag }} \
            /bin/bash -c "bin/ci_tests"

      - run: echo ${{ env.imagetag }} > imagetag

      - name: Cache imagetag
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/cache@v3
        env:
          cache-name: cache-imagetag
        with:
          path: imagetag
          key: image-cache-${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-${{ github.sha }}
